name: 'test'

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'

env:
  GOMAXPROCS: '7'

jobs:
  test:
    name: 'test'
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Check out code'
        uses: 'actions/checkout@v2'

      - uses: 'actions/setup-go@v2'
        with:
          go-version: '1.17'

      - uses: 'actions/cache@v2'
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-test-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-test-
            ${{ runner.os }}-go-

      - name: 'go-test'
        shell: 'bash'
        run: 'make test'

      - name: 'go-lint'
        shell: 'bash'
        run: 'make lint'
